app/controllers/chefs_controller.rb
app/models/chef.rb
db/migrate/20200622153419_create_chefs.rb
db/schema.rb
test/controllers/chefs_controller_test.rb
test/models/chef_test.rb

Hi guys. I have just added the Chef Model and Controller :)

Chef Controller and Model

---

Gemfile
Gemfile.lock
app/controllers/chefs_controller.rb
app/views/chefs/show.html.erb
db/seeds.rb

Added 100 chef seeds using Faker :)

Chef seeds added

---

app/assets/stylesheets/pages/_index.scss
app/controllers/chefs_controller.rb
app/views/chefs/index.html.erb

I recently initialized the index page.

initialized chef index

---

app/controllers/pages_controller.rb
db/migrate/20200622153830_add_fields_to_users.rb
db/schema.rb

Added user input fields, as drawing on lewagon schema

Adding user fields

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/chef/_banner.scss
app/assets/stylesheets/chef/_index.scss
app/assets/stylesheets/components/_index.scss
app/controllers/chefs_controller.rb
app/views/chefs/show.html.erb
db/schema.rb

Added Chef banner but it is still in progress

Chef banner added

---

app/assets/stylesheets/components/_index.scss
app/views/chefs/index.html.erb

styling of chef cards on index page

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/chefs_controller.rb
app/policies/application_policy.rb
app/policies/chef_policy.rb
app/views/chefs/new.html.erb
app/views/chefs/show.html.erb
app/views/pages/home.html.erb
db/migrate/20200622153830_add_fields_to_users.rb
test/policies/chef_policy_test.rb

I have pundit working on the features /new chef with a form to submit a new chef;
After one is created, it should have the options to update and delete.
Waiting for button on navbar, just tryed it with url paths

Implement pundit

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/chef/_banner.scss
app/assets/stylesheets/config/_fonts.scss
app/controllers/chefs_controller.rb
app/models/booking.rb
app/views/chefs/_bookings_form.html.erb
app/views/chefs/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
db/migrate/20200623135915_create_bookings.rb
db/schema.rb
db/seeds.rb
test/models/booking_test.rb

Show page with booking form done (Booking form is not connected yet though)

Show page and Booking Model

---

app/controllers/chefs_controller.rb
app/policies/chef_policy.rb

new chef save fixed

---

app/views/chefs/show.html.erb

Changed the back button to not be only a word

back button style changed

---

app/views/chefs/new.html.erb
app/views/devise/registrations/edit.html.erb

Changed button style on forms... I think i got them all

Styling user and chef show

---

app/views/shared/_navbar.html.erb

Linked options on dropdown avatar menu and home

avatar and home links set

---

app/views/devise/registrations/edit.html.erb

Link_to back to profile without an user id

removed user id for profile

---

app/controllers/bookings_controller.rb
app/views/devise/registrations/edit.html.erb

updated back btn on update page and remove rais on bokings controller

fixed update back btn and remove raise

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/bookings_controller.rb
app/controllers/chefs_controller.rb
app/views/chefs/show.html.erb
app/views/pages/home.html.erb

landing page improved

---

app/controllers/user_controller.rb

user model deleted

---

app/controllers/bookings_controller.rb
app/policies/booking_policy.rb
test/policies/booking_policy_test.rb

authorized user to book a chef

authorize user to book

---

app/controllers/bookings_controller.rb
app/controllers/pages_controller.rb
db/migrate/20200625101009_add_completed_to_bookings.rb
db/schema.rb

Bookings Controller methods added

Bookings Controller in progress

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/chef/_banner.scss
app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/pages_controller.rb
app/javascript/packs/application.js
app/javascript/plugins/flatpickr.js
app/views/chefs/_bookings_form.html.erb
app/views/chefs/show.html.erb
app/views/devise/registrations/edit.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb
package.json
yarn.lock

buttons, calendar and footer improved

buttons, calendar and footer improved

---

app/assets/stylesheets/chef/_banner.scss
app/assets/stylesheets/chef/_index.scss
app/controllers/chefs_controller.rb
app/views/chefs/show.html.erb

show page improvements

---

app/assets/stylesheets/chef/_chef_boxes.scss
app/assets/stylesheets/components/_footer.scss
app/views/chefs/show.html.erb

last changes show page
